services:
  rust:
    image: boiler_rust:latest
    networks:
      - main_net
      - monitor_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - RUST_PORT=${RUST_PORT}
      - RUST_LOG=${RUST_LOG}
      - SVELTE_URL=${SVELTE_URL}

  svelte:
    image: boiler_svelte:latest
    networks:
      - main_net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${SVELTE_PORT}

  caddy:
    image: boiler_caddy:latest
    networks:
      - main_net
    ports:
      - "80:80"
      - "443:443"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    command: sh -c "caddy run --config /etc/caddy/Caddyfile"
    environment:
      - CADDY_LOG_ROTATE_DAYS=356
      - CADDY_LOG_ROTATE_SIZE=10000
      - CADDY_DOMAIN=${CADDY_DOMAIN}
      - RUST_NAME=${RUST_NAME}
      - RUST_PORT=${RUST_PORT}
      - SVELTE_NAME=${SVELTE_NAME}
      - SVELTE_PORT=${SVELTE_PORT}
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/logs:/var/log/caddy
      - ./caddy/config/Caddyfile.local:/etc/caddy/Caddyfile

networks:
  main_net:
    driver: overlay
    name: main_net
  monitor_net:
    external: true
    name: monitor_net
