global:
  scrape_interval: 30m
  evaluation_interval: 1h
  scrape_timeout: 5m

scrape_configs:
  - job_name: "main_app-metrics"
    scheme: http
    metrics_path: "/metrics"
    static_configs:
      - targets: ["rust:3000"]
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance
  - job_name: "db-metrics"
    scheme: http
    metrics_path: "/metrics"
    static_configs:
      - targets: ["scylladb:9180"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
  - job_name: "search-metrics"
    scheme: http
    metrics_path: "/metrics"
    static_configs:
      - targets: ["meilisearch:7700"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
