global:
  scrape_interval: 15s
  evaluation_interval: 1m
  scrape_timeout: 10s

scrape_configs:
  - job_name: "main_app-metrics"
    scheme: http
    metrics_path: "/metrics"
    static_configs:
      - targets: ["rust:3000"]
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance

  - job_name: "scyllaDB-metrics"
    scheme: http
    metrics_path: "/metrics"
    static_configs:
      - targets: ["scylladb:9180"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: "meilisearch-metrics"
    scheme: http
    metrics_path: "/metrics"
    static_configs:
      - targets: ["meilisearch:7700"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
    authorization:
      type: Bearer
      credentials_file: /run/secrets/MEILI_ADMIN_KEY

  - job_name: "caddy"
    scheme: http
    metrics_path: "/metrics"
    static_configs:
      - targets: ["caddy:2019"]

  - job_name: "node_exporter"
    scheme: http
    metrics_path: "/metrics"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "redis-exporter"
    scheme: http
    metrics_path: "/metrics"
    static_configs:
      - targets: ["redis-exporter:9121"]
